language: python
cache: pip

env:
  global:
    - JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
    - PATH="$JAVA_HOME/bin:$PATH"

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -U tox pip virtualenv tox-travis
  - java -version

script:
  - tox